### ISSUE TITLE
Getting "subscritpionsClient.subscribe is not a function" error when trying to subscribe on the server.

### ISSUE THREAD

**Issue by shani117** [mikesparr/tutorial-graphql-subscriptions-redis#1]
Hi Mike,

Found your really helpful sample for subscriptions with Redis. When I cloned and ran it, ran into 2 issues.

1. moment dependency was missing in package.json so server crashed because of that. I added that to the package json and was able to successfully start the server.
2. Next, when I followed the steps in your repo and tried to subscribe to the messageAdded subscription, I kept getting this error - **subscriptionsClient.subscribe is not a function**

I found this issue when I searched for this: https://github.com/graphql-dotnet/server/issues/125 but the steps suggested in this don't seem to fix the issue in this server. Any pointers/ideas?

Best regards
Shani.

**Comment by mikesparr** [comment]
Hi @shani117 thanks for the feedback. I haven't looked at this repo in a while but I did add the momentJS dependency. 

I'm using a Mac and it sounds like your second issue may be Windows related. If that's the case, please share if you solve for others' benefit. Typically for environment-related issues which this sounds like, it may be best to try and deploy as Docker image to better control the environment. SEE: https://hub.docker.com/_/node/
